### ISSUE TITLE
allow players to disable the dehydration notification

### ISSUE THREAD

**Issue by Mumberthrax** [NerdNu/EasyRider#4]
stopping to water a horse can get annoying, especially if I don't feel like training it up any more than it already is. allow players to disable the annoying dehydration notification - at the very make it so that it can be set to only show upon first mounting the horse and not every 5 seconds or whatever it is.

**Comment by tompreuss** [comment]
@Mumberthrax you are now free to neglect your horse as you please: https://github.com/NerdNu/EasyRider/commit/34c51825f68d3500b70175eb84687219a6b9ecfe.

**Comment by totemo** [comment]
Thanks for drawing my attention to this issue.

Closed. Fixed.
