### ISSUE TITLE
Release for Minecraft Version 1.18+?

### ISSUE THREAD

**Issue by DnGXenon** [NerdNu/EasyRider#9]
I'm not sure what Minecraft version this plugin supports. When I try to use it on Minecraft 1.18. The plugin does not work. Internal Error. I didn't see anywhere in the original codepost what versions of Minecraft this supports. You will be getting a donation from me when this plugin get's updated Thanks!

**Comment by totemo** [comment]
If there's an internal error, there would be an exception trace in the server log. Please paste an extract showing the exception here. 

We're running this plugin on 1.18.1 (PaperSpigot) without a problem.

**Comment by DnGXenon** [comment]
after restarting the server to read the server log upon server load. It seems that there is no exception found. /easyrider help shows no results. Possible conflict with MMOHorse?

**Comment by totemo** [comment]
I can't help if you can't provide logs.

**Comment by totemo** [comment]
I've updated for 1.18.1, here: https://github.com/NerdNu/EasyRider/releases/tag/v1.19.0
